# Generated by Django 3.1.3 on 2021-02-01 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210129_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_liking',
            field=models.ManyToManyField(blank=True, related_name='posts_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
